"$schema" = "./node_modules/wrangler/config-schema.json"
name = "trmnl"
compatibility_date = "2026-07-23"
send_metrics = false

[[kv_namespaces]]
binding = "TRMNL_DEVICES"
id = "93fbad6022314b8995a3c5d952a0d7cf"

[[kv_namespaces]]
binding = "TRMNL_BOARD"
id = "5fd6e1078bfd4781bc1b0e379618e45e"

# [[analytics_engine_datasets]]
# binding = "TRMNL_ANALYTICS"
# id = "trmnl_analytics
