"$schema" = "./node_modules/wrangler/config-schema.json"
name = "trmnl"
compatibility_date = "2026-07-23"
send_metrics = false

[[kv_namespaces]]
binding = "TRMNL_DEVICES"
id = "trmnl_devices"

[[kv_namespaces]]
binding = "MSG_BOARD"
id = "msg_board"

# [[analytics_engine_datasets]]
# binding = "TRMNL_ANALYTICS"
# id = "trmnl_analytics
