"$schema" = "./node_modules/wrangler/config-schema.json"
name = "admin"
compatibility_date = "2026-07-23"
send_metrics = false

[[kv_namespaces]]
binding = "TRMNL_BOARD"
id = "trmnl_board"

# [[analytics_engine_datasets]]
# binding = "TRMNL_ANALYTICS"
# id = "trmnl_analytics
