"$schema" = "./node_modules/wrangler/config-schema.json"
name = "admin"
compatibility_date = "2026-07-23"
send_metrics = false

[[kv_namespaces]]
binding = "MESSAGES"
id = "trmnl_messages"

[[kv_namespaces]]
binding = "CALENDAR"
id = "trmnl_calendar"

# [[analytics_engine_datasets]]
# binding = "TRMNL_ANALYTICS"
# id = "trmnl_analytics
