"$schema" = "node_modules/wrangler/config-schema.json"
name = "trmnl-img"
main = "src/index.js"
compatibility_date = "2026-08-20"
upload_source_maps = true
send_metrics = false

[observability]
enabled = true

[[rules]]
type = "Data"
globs = ["**/*.woff", "**/*.woff2"]
fallthrough = true 

[[kv_namespaces]]
binding = "TRMNL_DEVICES"
id = "93fbad6022314b8995a3c5d952a0d7cf"

[[kv_namespaces]]
binding = "TRMNL_BOARD"
id = "5fd6e1078bfd4781bc1b0e379618e45e"